### ISSUE TITLE
2e kolom is onbenoemd en ongedocumenteerd

### ISSUE THREAD

**Issue by coret** [ivozandhuis/haarlem_kohier1887#2]
In het databestand (TSV) komt in de 2e kolom soms de waarde 1 voor, veelal is er geen waarde. In de documentatie is deze kolom niet benoemd en kan dus niet geïnterpreteerd worden.

**Comment by ivozandhuis** [comment]
Goed gezien :-) Leerzame oefening zo!!

**Comment by ivozandhuis** [comment]
Bestand aangepast.
